# yaml-language-server: $schema=https://aka.ms/winget-manifest.versionSchema
ManifestVersion: 1.5.0
Version: 0.3.8
Channel: ""
Paths:
  - RelativeFilePath: Alloomi_0.3.8_windows_amd64.exe
  - PortableCommandAlias: alloomi
InstallerLocale: en-US
Platform:
  - Windows.Desktop
Architecture:
  - x64
Installers:
  - InstallerUrl: https://github.com/melandlabs/release/releases/download/v0.3.8/Alloomi_0.3.8_x64-setup.exe
    InstallerSha256: f3df4ccd5028e9796b64b15b30c7b6f5814a0c1744d137d4e3ee0f9e1172c0df
    InstallerType: nsis
    UpgradeBehavior: install
    Scope: user
    InstallModes:
      - Interactive
      - Silent
      - SilentWithProgress
